name: Publish templates

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    uses: devcontainers/action@v1.3.0
    with:
      validate-only: true
      disable-repo-tagging: false
      publish-templates: true
      base-path-to-templates: "./src"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
