name: Build & publish Docker images

on:
  pull_request:
  workflow_dispatch:
    inputs:
      latest:
        description: "Push with tag 'latest'"
        required: false
        type: boolean

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          VERSION=v$(jq -r '.["version"]' ./src/smart-contracts-rust/devcontainer-template.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./resources/smart-contracts-rust
          push: true
          platforms: linux/amd64
          file: ./resources/smart-contracts-rust/Dockerfile
          tags: multiversx/devcontainer-smart-contracts-rust:${{ env.VERSION }}

      - name: Push to "latest"
        uses: docker/build-push-action@v3
        with:
          context: ./resources/smart-contracts-rust
          push: ${{ inputs.latest }}
          platforms: linux/amd64
          file: ./resources/smart-contracts-rust/Dockerfile
          tags: multiversx/devcontainer-smart-contracts-rust:latest
